export const GET_SIMPSONS = "GET_SIMPSONS";
export const GET_SIMPSONS_SUCCESS = "GET_SIMPSONS_SUCCESS";
export const GET_SIMPSONS_ERROR = "GET_SIMPSONS_ERROR";

export const ADD_SIMPSON = "ADD_SIMPSON";
export const ADD_SIMPSON_SUCCESS = "ADD_SIMPSON_SUCCESS";
export const ADD_SIMPSON_ERROR = "ADD_SIMPSON_ERROR";

export const REMOVE_SIMPSON = "REMOVE_SIMPSON";
export const REMOVE_SIMPSON_SUCCESS = "REMOVE_SIMPSON_SUCCESS";
export const REMOVE_SIMPSON_ERROR = "REMOVE_SIMPSON_ERROR";


export const MOVE_UP_SIMPSON = "MOVE_UP_SIMPSON";
export const MOVE_UP_SIMPSON_SUCCESS = "MOVE_UP_SIMPSON_SUCCESS";
export const MOVE_UP_SIMPSON_ERROR = "MOVE_UP_SIMPSON_ERROR";

export const MOVE_DOWN_SIMPSON = "MOVE_DOWN_SIMPSON";
export const MOVE_DOWN_SIMPSON_SUCCESS = "MOVE_DOWN_SIMPSON_SUCCESS";
export const MOVE_DOWN_SIMPSON_ERROR = "MOVE_DOWN_SIMPSON_ERROR";
